INSERT INTO ADDRESS(ADDITIONALINFO,STREET,CITYINFO_ZIP) VALUES ("private","Herlev Hovedgade 1",2730);
INSERT INTO ADDRESS(ADDITIONALINFO,STREET,CITYINFO_ZIP) VALUES ("private","Englandsvej 1",2300);
INSERT INTO ADDRESS(ADDITIONALINFO,STREET,CITYINFO_ZIP) VALUES ("private","Vejen 5",2820);
INSERT INTO ADDRESS(ADDITIONALINFO,STREET,CITYINFO_ZIP) VALUES ("private","Nybrovej 304",2800);
INSERT INTO ADDRESS(ADDITIONALINFO,STREET,CITYINFO_ZIP) VALUES ("public","Nørgaardsvej 30",2800);
INSERT INTO ADDRESS(ADDITIONALINFO,STREET,CITYINFO_ZIP) VALUES ("public","Nansensgade 19",1366);

INSERT INTO INFOENTITY(DTYPE,EMAIL,ADDRESS_ID) VALUES("PERSON","cphem@cphbusiness.dk",1);
INSERT INTO INFOENTITY(DTYPE,EMAIL,ADDRESS_ID) VALUES("PERSON","cphjm@cphbusiness.dk",2);
INSERT INTO INFOENTITY(DTYPE,EMAIL,ADDRESS_ID) VALUES("PERSON","cphlw@cphbusiness.dk",3);
INSERT INTO INFOENTITY(DTYPE,EMAIL,ADDRESS_ID) VALUES("PERSON","cphmr@cphbusiness.dk",4);
INSERT INTO INFOENTITY(DTYPE,EMAIL,ADDRESS_ID) VALUES("COMPANY","Apple@apple.com",5);
INSERT INTO INFOENTITY(DTYPE,EMAIL,ADDRESS_ID) VALUES("COMPANY","Microsoft@ms.com",6);

INSERT INTO PERSON(ID,FIRSTNAME,LASTNAME) VALUES (1,"Emma","Blomsterberg");
INSERT INTO PERSON(ID,FIRSTNAME,LASTNAME) VALUES (2,"Jonas","Machon");
INSERT INTO PERSON(ID,FIRSTNAME,LASTNAME) VALUES (3,"Lasse","Wenger");
INSERT INTO PERSON(ID,FIRSTNAME,LASTNAME) VALUES (4,"Mia","Ryvard");

INSERT INTO HOBBY(DESCRIPTION,HOBBY.NAME) VALUES("playing with af ball","Football");
INSERT INTO HOBBY(DESCRIPTION,HOBBY.NAME) VALUES("horse riding","Show jumping");
INSERT INTO HOBBY(DESCRIPTION,HOBBY.NAME) VALUES("stuff only old people do","Crochet");
INSERT INTO HOBBY(DESCRIPTION,HOBBY.NAME) VALUES("playing with a ball","Hockey");

INSERT INTO PERSON_HOBBY(hobbies_ID,persons_ID) VALUES(1,1);
INSERT INTO PERSON_HOBBY(hobbies_ID,persons_ID) VALUES(2,2);
INSERT INTO PERSON_HOBBY(hobbies_ID,persons_ID) VALUES(3,3);
INSERT INTO PERSON_HOBBY(hobbies_ID,persons_ID) VALUES(4,4);


INSERT INTO COMPANY(ID,CVR,DESCRIPTION,MARKETVALUE,COMPANY.NAME,NUMEMPLOYEES) VALUES(5,1234547634,"IT,Hardware,Software","","Apple","378234");
INSERT INTO COMPANY(ID,CVR,DESCRIPTION,MARKETVALUE,COMPANY.NAME,NUMEMPLOYEES) VALUES(6,4564356789,"IT,Hardware,Software","","Microsoft","347334");




INSERT INTO PHONE(DESCRIPTION,PHONE,INFOENTITY_ID) VALUES ("MOBIL","25346743",1);
INSERT INTO PHONE(DESCRIPTION,PHONE,INFOENTITY_ID) VALUES ("MOBIL","25343434",2);
INSERT INTO PHONE(DESCRIPTION,PHONE,INFOENTITY_ID) VALUES ("MOBIL","23246335",3);
INSERT INTO PHONE(DESCRIPTION,PHONE,INFOENTITY_ID) VALUES ("MOBIL","45632453",4);
INSERT INTO PHONE(DESCRIPTION,PHONE,INFOENTITY_ID) VALUES ("MOBIL","74343453",5);
INSERT INTO PHONE(DESCRIPTION,PHONE,INFOENTITY_ID) VALUES ("MOBIL","84335543",6);




